version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_AUTH_URL: ${NEXT_PUBLIC_AUTH_URL}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    env_file:
      - .env
    networks:
      - front_network
    ports:
      - 3000:3000
  auth-app:
    container_name: auth-app
    build:
      context: .
      dockerfile: ./apps/auth-app/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    env_file:
      - .env
    networks:
      - front_network
    ports:
      - 3002:3000
networks:
  front_network:
    external: true
